name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.2'
          - '2.3'
          - '2.4'
          - '2.5'
          - '2.6'
          - '2.7'
          - '3.0'
        activerecord:
          - '4.2'
          - '4.2.api'
          - '5.0'
          - '5.1'
          - '5.2'
        exclude:
          - ruby: '2.7'
            activerecord: '4.2'
          - ruby: '2.7'
            activerecord: '4.2.api'
    name: Ruby ${{ matrix.ruby }} / ActiveRecord ${{ matrix.activerecord }}
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: marginalia_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mysql:
        image: mysql:8
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: marginalia_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
       BUNDLE_GEMFILE: gemfiles/${{ matrix.activerecord }}.gemfile
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: |
          bundle exec rake db:reset test:all
        env:
          # PGHOST: localhost
          # PGUSER: postgres
          RAILS_ENV: test
